on: [push]

jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Validate OpenAPI definition

    steps:
      - name: Validate OpenAPI definition
        uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            swagger.yaml
