on: [push]

jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Validate OpenAPI definition

    steps:
      - uses: swaggerexpert/apidom-validate@v1
      - name: Validate OpenAPI definition
        with:
        definition-file: "swagger.yaml"
        fails-on: 2
